[package]
name = "aws-sign-v4"
version = "0.1.1"
description = "Generate AWS Signature 4 headers easily"
repository = "https://github.com/psnszsn/aws-sign-v4"
keywords = ["AWS", "Signature"]
license = "MIT"
readme = "README.md"
authors = ["Vlad Pănăzan <brgdvz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
url = "2.1.0"
hex = "0.4.0"
ring = "0.17.0-alpha.1"
http = "0.2.0"

[dev-dependencies]
reqwest = "0.10.0"
tokio = { version = "0.2", features = ["full"] }
